#!/bin/bash
# Interactive, self-documenting sweep of dpin_mode_value candidates.
#
# Requires a candidate with the runtime dpin_mode_value parameter (0112+)
# already installed, booted, and disarmed for future boots. Walks a list
# of values one at a time: sets the value, waits for you to plug the hub
# into the RIGHT port, captures logs, checks whether the test actually
# ran (not just whether it crashed), asks whether a picture appeared,
# and appends+commits+pushes a result to notes/mode-value-sweep-results.md.
#
# Usage:
#   scripts/sweep-mode-value.sh              # sweep the default remaining set
#   scripts/sweep-mode-value.sh 2 3 4 5      # sweep only these values
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RESULTS="$REPO/notes/mode-value-sweep-results.md"
PARAM=/sys/module/thunderbolt_apple/parameters/dpin_mode_value
CAPDIR="$REPO/captures"
TODAY="$(date +%Y-%m-%d)"

if [ ! -w "$PARAM" ] && [ ! -e "$PARAM" ]; then
	echo "ERROR: $PARAM does not exist. A 0112+ candidate must be installed and booted first." >&2
	exit 1
fi

mkdir -p "$CAPDIR"
[ -f "$RESULTS" ] || {
	echo "# dpin_mode_value sweep results" > "$RESULTS"
	echo "" >> "$RESULTS"
	echo "Auto-generated by scripts/sweep-mode-value.sh. One entry per attempt." >> "$RESULTS"
	echo "" >> "$RESULTS"
}

# Default: values not yet cleanly tested as of 2026-09-23 (0,9,10 clean
# negatives from prior candidates; 8 clean negative; 1 needs a valid
# retest; 2-7,11-15 unexplored).
default_values=(1 2 3 4 5 6 7 11 12 13 14 15)
if [ "$#" -gt 0 ]; then
	queue=("$@")
else
	queue=("${default_values[@]}")
fi

require_unplugged() {
	while ls /sys/bus/thunderbolt/devices/ 2>/dev/null | grep -qv '^domain0$'; do
		echo "Hub still appears connected on the Thunderbolt bus."
		read -rp "Unplug it from the right port, then press Enter... " _
	done
	local edp
	edp=$(cat /sys/class/drm/card2-eDP-1/status 2>/dev/null || echo unknown)
	if [ "$edp" != "connected" ]; then
		echo "WARNING: eDP status is '$edp', not 'connected'. Stop and check before continuing." >&2
		read -rp "Continue anyway? [y/N] " go
		[ "${go:-N}" = "y" ] || [ "${go:-N}" = "Y" ] || exit 1
	fi
}

log() { printf '%s\n' "$*" >> "$RESULTS"; }

i=0
while [ "$i" -lt "${#queue[@]}" ]; do
	v="${queue[$i]}"
	i=$((i + 1))
	echo
	echo "=== dpin_mode_value=$v ==="
	require_unplugged

	echo "$v" | sudo -n tee "$PARAM" >/dev/null
	actual="$(sudo -n cat "$PARAM")"
	if [ "$actual" != "$v" ]; then
		echo "ERROR: parameter write did not stick (wrote $v, read back $actual). Stopping." >&2
		exit 1
	fi

	echo "dpin_mode_value=$v is set. Connect the hub to the RIGHT USB-C port now"
	echo "(monitor already attached to the hub)."
	read -rp "Press Enter once connected... " _

	echo "Waiting 10s for HPD/AUX/DPRX/hotplug to settle..."
	sleep 10

	stamp="$(date +%Y-%m-%d-%H%M%S)"
	klog="$CAPDIR/${stamp}-sweep-mv${v}-kernel.log"
	sudo -n journalctl -k -b --no-pager -o short-monotonic > "$klog"

	ran=$(grep -c "native DPIN0: active=1 handshake=" "$klog" || true)
	hotplug=$(grep -c "cb_hotplug() connected:1" "$klog" || true)
	connect_call=$(grep -c "dcp_dptx_connect(port=" "$klog" || true)
	edp_now=$(cat /sys/class/drm/card2-eDP-1/status 2>/dev/null || echo unknown)

	valid=1
	if [ "$ran" -eq 0 ] || [ "$hotplug" -eq 0 ] || [ "$connect_call" -eq 0 ]; then
		valid=0
		echo
		echo "WARNING: this attempt looks INVALID, not a real negative:"
		echo "  native DPIN0 handshake ran:  $([ "$ran" -gt 0 ] && echo yes || echo NO)"
		echo "  DCP hotplug detected:        $([ "$hotplug" -gt 0 ] && echo yes || echo NO)"
		echo "  dcp_dptx_connect() called:   $([ "$connect_call" -gt 0 ] && echo yes || echo NO)"
		echo "This can happen from AUX/DPRX flakiness upstream of our own code,"
		echo "independent of dpin_mode_value. Recommend retrying this exact value."
		read -rp "Retry dpin_mode_value=$v now? [Y/n] " retry
		if [ "${retry:-Y}" != "n" ] && [ "${retry:-Y}" != "N" ]; then
			echo "Please unplug the hub, then we'll retry."
			read -rp "Press Enter once unplugged... " _
			queue=("${queue[@]:0:$i}" "$v" "${queue[@]:$i}")
			log "## dpin_mode_value=$v -- $(date -Iseconds) -- INVALID, retrying"
			log "- handshake ran: $([ "$ran" -gt 0 ] && echo yes || echo no), hotplug: $([ "$hotplug" -gt 0 ] && echo yes || echo no), connect_call: $([ "$connect_call" -gt 0 ] && echo yes || echo no)"
			log "- kernel log: captures/$(basename "$klog") (untracked)"
			log ""
			continue
		fi
	fi

	pic="n"
	if [ "$valid" -eq 1 ]; then
		read -rp "Did a picture appear on the external monitor? [y/N] " pic
	else
		echo "Proceeding without asking (attempt marked invalid); not a real data point."
	fi
	read -rp "Any notes? (Enter for none) " notes

	log "## dpin_mode_value=$v -- $(date -Iseconds)"
	log "- valid attempt: $([ "$valid" -eq 1 ] && echo yes || echo no)"
	log "- picture: ${pic:-N}"
	log "- handshake ran: $([ "$ran" -gt 0 ] && echo yes || echo no)"
	log "- hotplug detected: $([ "$hotplug" -gt 0 ] && echo yes || echo no)"
	log "- dcp_dptx_connect called: $([ "$connect_call" -gt 0 ] && echo yes || echo no)"
	log "- eDP status after: $edp_now"
	log "- notes: ${notes:-none}"
	log "- kernel log: captures/$(basename "$klog") (untracked, private)"
	log ""

	cd "$REPO"
	git add "$RESULTS"
	git commit -q -m "Sweep: dpin_mode_value=$v result ($([ "$valid" -eq 1 ] && echo valid || echo invalid), picture=${pic:-N})"
	git push -q

	if [ "$valid" -eq 1 ] && { [ "$pic" = "y" ] || [ "$pic" = "Y" ]; }; then
		echo
		echo "*** PICTURE REPORTED at dpin_mode_value=$v. Stopping the sweep here. ***"
		echo "Leave the hub connected and tell the assistant so this can be confirmed"
		echo "and locked in properly (no further register writes should happen until then)."
		exit 0
	fi

	echo "Logged and pushed. Please unplug the hub before the next value."
	read -rp "Press Enter once unplugged... " _
done

echo
echo "Sweep complete. See $RESULTS"
